api/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^cases/new$", "api.views.new_case"),
    url(r"^cases/show$", "api.views.show_case"),
    url(r"^images/new$", "api.views.new_image"),
    url(r"^images/report", "api.views.get_report"),
)

ghiro/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r"^$", "analyses.views.dashboard"),
    (r"^users/", include("users.urls")),
    (r"^analyses/", include("analyses.urls")),
    (r"^hashes/", include("hashes.urls")),
    (r"^system/", include("system.urls")),
    (r"^api/", include("api.urls")),
)

hashes/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^index/$", "hashes.views.list_hashes"),
    url(r"^new/", "hashes.views.new_hashes"),
    url(r"^show/(?P<list_id>[\d]+)/", "hashes.views.show_hashes"),
    url(r"^delete/(?P<list_id>[\d]+)/", "hashes.views.delete_hashes"),
)

hashes/models.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.db import models

from analyses.models import Profile, Analysis

class List(models.Model):
    """Hashes list."""
    CIPHERS = (
            ("sha1", "SHA1"),
            ("sha224", "SHA224"),
            ("sha384", "SHA384"),
            ("crc32", "CRC32"),
            ("sha256", "SHA256"),
            ("sha512", "SHA512"),
            ("md5", "MD5")
            )
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    cipher = models.CharField(max_length=6, choices=CIPHERS, db_index=True, null=False, blank=False, default="MD5")
    public = models.BooleanField(default=False)
    owner = models.ForeignKey(Profile, null=False, blank=False, on_delete=models.CASCADE, db_index=True, editable=False, related_name="owned_hashes")
    created_at = models.DateTimeField(auto_now_add=True, editable=False, db_index=True)
    matches = models.ManyToManyField(Analysis, blank=True)

    def is_owner(self, user):
        """Checks if an user is the owner of this object.
        @param user: user instance
        @return: boolean permission
        """
        return user == self.owner

    def can_read(self, user):
        """Checks if an user is allowed to read this object.
        @param user: user instance
        @return: boolean permission
        """
        return user.is_superuser or self.is_owner(user) or self.public

    def can_write(self, user):
        """Checks if an user is allowed to write (create, edit, delete) this object.
        @param user: user instance
        @return: boolean permission
        """
        return user.is_superuser or self.is_owner(user)

class Hash(models.Model):
    """Hashes."""
    value = models.CharField(max_length=255)
    list = models.ForeignKey(List, null=False, blank=False, on_delete=models.CASCADE, db_index=True, editable=False)

hashes/forms.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

import re
from django import forms

from hashes.models import List

class ListForm(forms.ModelForm):
    """Hash list form."""
    hash_list = forms.FileField(required=True)

    class Meta:
        model = List
        fields = "__all__"

    def clean_hash_list(self):
        file = self.cleaned_data["hash_list"]
        cipher = self.cleaned_data["cipher"].lower()

        # Checks file for validation line by line.
        line_count = 1
        for row in file.readlines():
            # Skip comments.
            if row.startswith("#"):
                continue
            # Skip empty lines.
            if len(row) == 0:
                continue
            # MD5.
            if cipher == "md5":
                if not re.match(r"^([a-fA-F\d]{32})$", row):
                    raise forms.ValidationError("Uploaded file does not met MD5 hash format: [a-fA-F\\d]{32} in line %s" % line_count)
            # CRC32
            elif cipher == "crc32":
                if not re.match(r"^([a-fA-F\d]{8})$", row):
                    raise forms.ValidationError("Uploaded file does not met CRC32 hash format: [a-fA-F\\d]{8} in line %s" % line_count)
            # SHA1.
            elif cipher == "sha1":
                if not re.match(r"^([a-fA-F\d]{40})$", row):
                    raise forms.ValidationError("Uploaded file does not met SHA1 hash format: [a-fA-F\\d]{40} in line %s" % line_count)
            # SHA224.
            elif cipher == "sha224":
                if not re.match(r"^([a-fA-F\d]{56})$", row):
                    raise forms.ValidationError("Uploaded file does not met SHA224 hash format: [a-fA-F\\d]{56} in line %s" % line_count)
            # SHA384.
            elif cipher == "sha384":
                if not re.match(r"^([a-fA-F\d]{96})$", row):
                    raise forms.ValidationError("Uploaded file does not met SHA386 hash format: [a-fA-F\\d]{96} in line %s" % line_count)
            # SHA256.
            elif cipher == "sha256":
                if not re.match(r"^([a-fA-F\d]{64})$", row):
                    raise forms.ValidationError("Uploaded file does not met SHA256 hash format: [a-fA-F\\d]{64} in line %s" % line_count)
            # SHA512.
            elif cipher == "sha512":
                if not re.match(r"^([a-fA-F\d]{128})$", row):
                    raise forms.ValidationError("Uploaded file does not met SHA512 hash format: [a-fA-F\\d]{128} in line %s" % line_count)

            line_count += 1

        return file

hashes/views.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

import hashes.forms as forms
from hashes.models import List, Hash
from ghiro.common import log_activity

@require_safe
@login_required
def list_hashes(request):
    """Hash list index."""

    my_lists = List.objects.filter(owner=request.user)
    public_lists = List.objects.filter(public=True)

    # Set sidebar active tab.
    request.session["sidebar_active"] = "side-hashes"

    return render_to_response("hashes/index.html",
                              {"my_lists": my_lists, "public_lists": public_lists},
                              context_instance=RequestContext(request))

@login_required
def new_hashes(request):
    """New hash list."""

    if request.method == "POST":
        form = forms.ListForm(request.POST, request.FILES)

        if form.is_valid():
            list = form.save(commit=False)
            list.owner = request.user
            list.save()
            # Read file.
            with open(request.FILES["hash_list"].temporary_file_path(), "r") as file:
                for row in file.readlines():
                    Hash.objects.get_or_create(value=row.strip(), list=list)

            # Auditing.
            log_activity("H",
                         "Created new hash list %s" % list.name,
                         request)

            return HttpResponseRedirect(reverse("hashes.views.show_hashes", args=(list.id,)))
    else:
        form = forms.ListForm()

    return render_to_response("hashes/new.html",
                              {"form": form},
                              context_instance=RequestContext(request))

@require_safe
@login_required
def show_hashes(request, list_id):
    hash_list = get_object_or_404(List, pk=list_id)

    # Security check.
    if request.user != hash_list.owner:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to show this."},
                                  context_instance=RequestContext(request))

    return render_to_response("hashes/show.html",
                              {"hash_list": hash_list},
                              context_instance=RequestContext(request))

@require_safe
@login_required
def delete_hashes(request, list_id):
    hash_list = get_object_or_404(List, pk=list_id)

    # Security check.
    if request.user != hash_list.owner:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to delete this."},
                                  context_instance=RequestContext(request))

    hash_list.delete()

    # Auditing.
    log_activity("H",
                 "Deleted hash list %s" % hash_list.name,
                 request)

    return HttpResponseRedirect(reverse("hashes.views.list_hashes"))

templates/hashes/index.html
{% extends "base.html" %}

{% block content %}

    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li class="active">
                Hashes
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>Hashes <small>hashes list management</small></h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <div class="header-control pull-right">
                    <a href="{% url "hashes.views.new_hashes" %}"  type="button" class="btn btn-success pull-right" title="Add list" data-tooltip="tooltip" data-placement="left">
                        <span class="glyphicon glyphicon-plus"></span>
                    </a>
                </div>
                <ul class="nav nav-pills nav-primary" id="cases_tab">
                    <li class="active">
                        <a href="#my" data-toggle="tab">My</a>
                    </li>
                    <li>
                        <a href="#all" data-toggle="tab">All</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="my">
                        <div class="box">
                            <table class="table datatables">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Cipher</th>
                                        <th>Created at</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for list in my_lists %}
                                        <tr>
                                            <td><a href="{% url "hashes.views.show_hashes" list.id %}">{{ list.name }}</a></td>
                                            <td>{{ list.get_cipher_display }}</td>
                                            <td>{{ list.created_at }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    {% if request.user == list.owner or request.user.is_superuser %}
                                                        <a class="btn btn-danger btn-trash" data-tooltip="tooltip"  title="Delete" href="#trash" role="button" data-toggle="modal" id="{% url "hashes.views.delete_hashes" list.id %}">
                                                            <span class="glyphicon glyphicon-trash"></span>
                                                        </a>
                                                    {% else %}
                                                        <a class="btn btn-danger" title="You are not authorized to delete this" disabled="disabled">
                                                            <span class="glyphicon glyphicon-trash"></span>
                                                        </a>
                                                    {% endif %}
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane" id="all">
                        <div class="box">
                           <table class="table datatables">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Cipher</th>
                                        <th>Created at</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for list in public_lists %}
                                    <tr>
                                        <td><a href="{% url "hashes.views.show_hashes" list.id %}">{{ list.name }}</a></td>
                                        <td>{{ list.get_cipher_display }}</td>
                                        <td>{{ list.created_at }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-danger btn-trash tool" href="#trash" role="button" data-toggle="modal" id="" title="Delete hash">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                        {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="trash" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Delete hash list</h4>
                </div>
                <div class="modal-body">
                    This <b>permanently</b> deletes the selected hash list.
                    Are you sure continue?
                </div>
                <div class="modal-footer">
                    <a type="button" class="btn btn-danger" id="id">Delete</a>
                    <a type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $('.datatables').dataTable({
            "sPaginationType": "bs_normal",
            "sDom": '<"row view-filter"<"col-sm-12"<"clearfix">>>t<"row view-pager"<"col-sm-12"<"text-right"p>>>',
            "aaSorting": [[ 2, "desc" ]]
        });

        $('.btn-trash').click(function(){
            var id = $(this).attr("id");
            $("#id").attr({href: id});
        });
    </script>

{%  endblock %}

templates/hashes/new.html
{% extends "base.html" %}

{% block content %}

    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li>
                <a href="{% url "hashes.views.list_hashes" %}"><span class="glyphicon glyphicon-book gi-0x"></span> </i> Hashes</a>
            </li>
            <li class="active">
                New hash list
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>Hashes</h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <div class="wdgt-header">Complete the following form for to create a new hash list</div>
                <div class="wdgt-body">
                    <form action="{% url "hashes.views.new_hashes" %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group form-inline">
                            {{ form.non_field_errors }}
                            Name
                            <div class="controls box">
                                {{ form.name }}<span class="help-inline">{{ form.name.errors }}</span>
                            </div>
                            Description
                            <div class="controls box">
                                <textarea id="id_description" rows="3" name="description" style="width: 350px"></textarea><span class="help-inline">{{ form.description.errors }}</span>
                            </div>
                            Cipher
                            <div class="controls box">
                                {{ form.cipher }}<span class="help-inline">{{ form.cipher.errors }}</span>
                            </div>
                            <div class="box">
                                {{ form.public }} Public - <small> shared with other users</small>
                                <span class="help-inline">{{ form.public.errors }}</span>
                            </div>
                            <div class="controls box">
                                File {{ form.hash_list }}<span class="help-inline">{{ form.hash_list.errors }}</span>
                            </div>
                            <div class="form-actions">
                                <button id="btn_submit" type="submit" class="btn btn-success">
                                    Save
                                </button>
                                <a href="{% url "hashes.views.list_hashes" %}" class="btn btn-default"> Back </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/hashes/show.html
{% extends "base.html" %}

{% block content %}

    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li>
                <a href="{% url "hashes.views.list_hashes" %}"><span class="glyphicon glyphicon-list-alt gi-0x"></span> Hashes</a>
            </li>
            <li class="active">
                {{ hash_list.name }}
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>{{ hash_list.name }} <small>details about this hash list</small></h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <dl class="dl-horizontal">
                    {% if hash_list.description %}
                    <dt>
                        Description:
                    </dt>
                    <dd>
                        {{ hash_list.description }}&nbsp;
                    </dd>
                    {% endif %}
                    <dt>
                        Chiper:
                    </dt>
                    <dd>
                        {{ hash_list.cipher|upper }}&nbsp;
                    </dd>
                    <dt>
                        Public:
                    </dt>
                    <dd>
                        {% if hash_list.public %}
                            <span class="glyphicon glyphicon-ok-circle text-success"> </span>
                        {% else %}
                            <span class="glyphicon glyphicon-remove-circle text-danger"></span>
                        {% endif %}
                    </dd>
                    <dt>
                        Owner:
                    </dt>
                    <dd>
                        {{ hash_list.owner }}&nbsp;
                    </dd>
                    <dt>
                        Created:
                    </dt>
                    <dd>
                        {{ hash_list.created_at }}&nbsp;
                    </dd>
                </dl>
                <table class="table datatables">
                    <thead>
                        <tr>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for hash in hash_list.hash_set.all %}
                        <tr>
                            <td>{{ hash.value }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<script type="text/javascript">
$('.datatables').dataTable({
    "sPaginationType": "bs_normal",
    "sDom": '<"row view-filter"<"col-sm-12"<"clearfix">>>t<"row view-pager"<"col-sm-12"<"text-right"p>>>',
    "aLengthMenu": [[1000, 10000, -1], [1000, 10000, "All"]]
});
</script>

{%  endblock %}