analyses/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^cases/$", "analyses.views.list_cases"),
    url(r"^cases/new/", "analyses.views.new_case"),
    url(r"^cases/edit/(?P<case_id>[\d]+)/", "analyses.views.edit_case"),
    url(r"^cases/close/(?P<case_id>[\d]+)/", "analyses.views.close_case"),
    url(r"^cases/delete/(?P<case_id>[\d]+)/", "analyses.views.delete_case"),
    url(r"^cases/show/(?P<case_id>[\d]+)/(?P<page_name>[\w]+)/", "analyses.views.show_case"),
    url(r"^cases/(?P<case_id>[\d]+)/images/new/$", "analyses.views.new_image"),
    url(r"^cases/(?P<case_id>[\d]+)/folder/new/$", "analyses.views.new_folder"),
    url(r"^cases/(?P<case_id>[\d]+)/url/new/$", "analyses.views.new_url"),
    url(r"^cases/count_ajax/(?P<case_id>[\d]+)/(?P<analysis_id>[\d]+)/$", "analyses.views.count_new_analysis"),
    url(r"^show/(?P<analysis_id>[\d]+)/$", "analyses.views.show_analysis"),
    url(r"^show/(?P<analysis_id>[\d]+)/hexdump/$", "analyses.views.hex_dump"),
    url(r"^delete/(?P<analysis_id>[\d]+)/$", "analyses.views.delete_analysis"),
    url(r"^images/(?P<page_name>[\w]+)/$", "analyses.views.list_images"),
    url(r"^images/file/(?P<id>[\d\w]+)/$", "analyses.views.image"),
    url(r"^images/favorite/(?P<id>[\d\w]+)/$", "analyses.views.favorite"),
    url(r"^images/comment/(?P<id>[\d]+)/$", "analyses.views.add_comment"),
    url(r"^images/comment/delete/(?P<id>[\d]+)/$", "analyses.views.delete_comment"),
    url(r"^search/(?P<page_name>[\w]+)/$", "analyses.views.search"),
    url(r"^images/tag/add/(?P<id>[\d]+)/$", "analyses.views.add_tag"),
    url(r"^images/tag/delete/(?P<id>[\d]+)/$", "analyses.views.delete_tag"),
    url(r"^show/(?P<analysis_id>[\d]+)/report/(?P<report_type>[\w]+)/$", "analyses.views.static_report"),
    url(r"^show/(?P<analysis_id>[\d]+)/export/json/$", "analyses.views.export_json"),
)

api/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^cases/new$", "api.views.new_case"),
    url(r"^cases/show$", "api.views.show_case"),
    url(r"^images/new$", "api.views.new_image"),
    url(r"^images/report", "api.views.get_report"),
)

ghiro/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r"^$", "analyses.views.dashboard"),
    (r"^users/", include("users.urls")),
    (r"^analyses/", include("analyses.urls")),
    (r"^hashes/", include("hashes.urls")),
    (r"^system/", include("system.urls")),
    (r"^api/", include("api.urls")),
)

users/models.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from uuid import uuid4
from django.db import models
from django.contrib.auth.models import AbstractUser

class Profile(AbstractUser):
    """User profile."""

    api_key = models.CharField(default=uuid4, max_length=36, null=False, blank=False, unique=True, db_index=True)

class Activity(models.Model):
    """Audits users activities."""

    CATEGORIES = (
        ("A", "Admin"),
        ("I", "Analysis"),
        ("H", "Hash List"),
        ("C", "Case")
        )
    message = models.TextField(null=False, blank=False)
    category = models.CharField(max_length=1, choices=CATEGORIES, db_index=True, editable=False, null=False, blank=False)
    user = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE, db_index=True, editable=False)
    source_ip = models.GenericIPAddressField(null=False, blank=False)
    forwarded_for_ip = models.GenericIPAddressField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, db_index=True)

    class Meta:
        ordering = ["-created_at"]

analyses/forms.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

import os

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator

from analyses.models import Case, Analysis, Comment
from ghiro.common import check_allowed_content
from lib.utils import get_content_type_from_file

class CaseForm(forms.ModelForm):
    """Case form."""
    class Meta:
        model = Case
        fields = "__all__"

class CommentForm(forms.ModelForm):
    """Comment form."""
    class Meta:
        model = Comment
        fields = "__all__"

class UploadImageForm(forms.ModelForm):
    """Image upload form."""
    image = forms.FileField(required=True)

    class Meta:
        model = Analysis
        fields = ["image"]

    def clean_image(self):
        image = self.cleaned_data.get("image", False)
        if image:
            # File check.
            if image._size > settings.MAX_FILE_UPLOAD:
                raise ValidationError("Image file too large")
            # Type check.
            file_type = get_content_type_from_file(image.temporary_file_path())
            if not check_allowed_content(file_type):
                raise ValidationError("Image type not supported.")
        else:
            raise ValidationError("Image field is mandatory.")

class ImageFolderForm(forms.Form):
    """Folder upload form."""
    path = forms.CharField(required=True)

    def clean_image(self):
        path = self.cleaned_data.get("path", False)
        if path:
            # Checks if it exist.
            if not os.path.exists(path):
                raise ValidationError("Specified path not found.")
            # Checks if is a directory.
            if not os.path.isdir(path):
                raise ValidationError("Specified path is not a directory.")
        else:
            raise ValidationError("URL field is mandatory.")

class UrlForm(forms.Form):
    """Image url form."""
    url = forms.CharField(required=True)

    def clean_url(self):
        url = self.cleaned_data.get("url", False)
        if url:
            validate = URLValidator()
            try:
                validate(url)
            except ValidationError:
                raise ValidationError("Please enter a valid URL")
        else:
            raise ValidationError("Path field is mandatory.")

analyses/views.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

import gridfs
import os
import re
import requests
import json
from bson.son import SON
from bson.objectid import ObjectId, InvalidId
from django.template import RequestContext, loader, Context
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe, require_POST
from django.shortcuts import render_to_response, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.utils.timezone import now
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.utils.encoding import force_text
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile

import analyses.forms as forms
from analyses.models import Case, Analysis, Favorite, Comment, Tag
from lib.db import save_file, get_file, mongo_connect
from lib.utils import create_thumb, hexdump, get_content_type_from_file
from users.models import Profile
from ghiro.common import log_activity, check_allowed_content

try:
    import pdfkit
    HAVE_PDFKIT = True
except ImportError:
    HAVE_PDFKIT = False

# Mongo connection.
db = mongo_connect()
fs = gridfs.GridFS(db)

@login_required
def new_case(request):
    """Creates a new case."""
    if request.method == "POST":
        form = forms.CaseForm(request.POST)
        if form.is_valid():
            case = form.save(commit=False)
            case.owner = request.user
            case.save()
            form.save_m2m()
            # Always add owner.
            case.users.add(request.user)
            # Auditing.
            log_activity("C",
                         "Created new case %s" % case.name,
                         request)
            return HttpResponseRedirect(reverse("analyses.views.show_case", args=(case.id, "list")))
    else:
        form = forms.CaseForm()

    return render_to_response("analyses/cases/new.html",
                              {"form": form},
                              context_instance=RequestContext(request))

@login_required
def edit_case(request, case_id):
    """Edit a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if request.user != case.owner and not request.user.is_superuser:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to edit this."},
                                  context_instance=RequestContext(request))

    if case.state == "C":
        return render_to_response("error.html",
                                  {"error": "You cannot edit a closed case."},
                                  context_instance=RequestContext(request))

    if request.method == "POST":
        form = forms.CaseForm(request.POST, instance=case)
        if form.is_valid():
            case = form.save(commit=False)
            case.owner = request.user
            case.updated_at = now()
            case.save()
            form.save_m2m()
            # Always add owner.
            case.users.add(request.user)
            # Auditing.
            log_activity("C",
                         "Edited case %s" % case.name,
                         request)
            return HttpResponseRedirect(reverse("analyses.views.show_case", args=(case.id, "list")))
    else:
        form = forms.CaseForm(instance=case)

    # Redirects to case index if requested.
    if request.GET.get("page", None):
        return HttpResponseRedirect(reverse("analyses.views.list_cases"))
    else:
        return render_to_response("analyses/cases/edit.html",
                                  {"form": form, "case": case},
                                  context_instance=RequestContext(request))

@login_required
def close_case(request, case_id):
    """Close a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if request.user != case.owner and not request.user.is_superuser:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to close this. Only owner can close the case."},
                                  context_instance=RequestContext(request))

    if case.state == "C":
        return render_to_response("error.html",
                                  {"error": "You cannot edit an already closed case."},
                                  context_instance=RequestContext(request))

    case.state = "C"
    case.updated_at = now()
    case.save()
    # Auditing.
    log_activity("C",
                 "Closed case %s" % case.name,
                 request)
    return HttpResponseRedirect(reverse("analyses.views.list_cases"))

@require_safe
@login_required
def delete_case(request, case_id):
    """Delete a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if request.user != case.owner and not request.user.is_superuser:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to delete this. Only owner can delete the case."},
                                  context_instance=RequestContext(request))

    # Delete all analysis.
    for image in case.images.all():
        image.delete()
    # Delete case.
    Case.objects.get(pk=case_id).delete()

    # Auditing.
    log_activity("C",
                 "Case %s deleted" % case.name,
                 request)
    return HttpResponseRedirect(reverse("analyses.views.list_cases"))

@require_safe
@login_required
def show_case(request, case_id, page_name):
    """Details about a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if not request.user in case.users.all() and not request.user.is_superuser:
        return render_to_response("error.html",
            {"error": "You are not authorized to view this."},
            context_instance=RequestContext(request))

    tasks = Analysis.objects.filter(case=case)

    # Get last image.
    if tasks.filter(state="C").order_by("completed_at").exists():
        last_image = tasks.filter(state="C").order_by("-id")[0].id
    else:
        last_image = 0

    # Filter by status if requested.
    filtering = request.GET.get("filter")
    if filtering == "completed":
        tasks = tasks.filter(Q(state="C") | Q(state="F"))
    page = request.GET.get("page")
    if page_name == "list" or page_name == "thumb":
        tasks = _paginate(tasks, page, 20)
    elif page_name == "owned":
        tasks = tasks.filter(owner=request.user)
        tasks = _paginate(tasks, page, 20)
    elif page_name == "others":
        tasks = tasks.exclude(owner=request.user)
        tasks = _paginate(tasks, page, 20)
    elif page_name == "favorites":
        tasks = tasks.filter(favorites__owner=request.user)
        tasks = _paginate(tasks, page, 20)
    elif page_name == "map":
        # Return all data, lookup on mongo to be faster.
        mongo_results = db.analyses.find({"metadata.gps.pos": {"$exists": True}})
        # Get results (run a bunch of queries to avoid too long sql queries).
        tasks = []
        for result in mongo_results:
            try:
                analyses = Analysis.objects.filter(case=case)
                if not request.user.is_superuser:
                    analyses = analyses.filter(Q(case__owner=request.user) | Q(case__users=request.user))
                tasks.append(analyses.get(analysis_id=result["_id"]))
            except ObjectDoesNotExist:
                continue
    elif page_name == "nude":
        # Return all data, lookup on mongo to be faster.
        mongo_results = db.analyses.find({"nude.nudepy.result": True})
        # Get results (run a bunch of queries to avoid too long sql queries).
        tasks = []
        for result in mongo_results:
            try:
                analyses = Analysis.objects.filter(case=case)
                if not request.user.is_superuser:
                    analyses = analyses.filter(Q(case__owner=request.user) | Q(case__users=request.user))
                tasks.append(analyses.get(analysis_id=result["_id"]))
            except ObjectDoesNotExist:
                continue
        tasks = _paginate(tasks, page, 20)
    elif page_name == "search":
        pass
    else:
        raise Exception

    return render_to_response("analyses/cases/show.html",
                              {"case": case, "tasks": tasks, "last_image": last_image, "pagename": page_name, "filtered": filtering},
                              context_instance=RequestContext(request))

@require_safe
@login_required
def count_new_analysis(request, case_id, analysis_id):
    """Count new analysis."""
    case = get_object_or_404(Case, pk=case_id)
    new_analysis_count = Analysis.objects.filter(case=case).filter(state="C").filter(pk__gt=analysis_id).count()
    return HttpResponse(new_analysis_count)

@require_safe
@login_required
def list_cases(request):
    """Cases index."""
    last = Case.objects.all()
    my = Case.objects.filter(owner=request.user)
    others = Case.objects.exclude(owner=request.user)

    # Only superuser can see all.
    if not request.user.is_superuser:
        last = last.filter(users=request.user)

    # Set sidebar active tab.
    request.session["sidebar_active"] = "side-cases"

    return render_to_response("analyses/cases/index.html",
                              {"my_cases": my, "last_cases": last, "others_cases": others},
                              context_instance=RequestContext(request))

@login_required
def new_image(request, case_id):
    """Upload a new image."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if not request.user.is_superuser and not request.user in case.users.all():

templates/analyses/report/_dashboardAnalysisResult.html
<table class="table">
    <thead>
        <tr>
            <th>Type</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Static analysis</td>
            <td><span class="label label-success">Static data</span></td>
        </tr>
        <tr>
            <td>EXIF metadata extraction</td>
            <td> {% if analysis.report.metadata.Exif %} <span class="label label-success">EXIF Metadata</span> {% else %} <span class="label label-dark">No EXIF metadata</span> {% endif %} </td>
        </tr>
        <tr>
            <td>IPTC metadata extraction</td>
            <td> {% if analysis.report.metadata.Iptc %} <span class="label label-success">IPTC Metadata</span> {% else %} <span class="label label-dark">No IPTC metadata</span> {% endif %} </td>
        </tr>
        <tr>
            <td>XMP metadata extraction</td>
            <td> {% if analysis.report.metadata.Xmp %} <span class="label label-success">XMP Metadata</span> {% else %} <span class="label label-dark">No XMP metadata</span> {% endif %} </td>
        </tr>
        <tr>
            <td>Preview extraction from metadata</td>
            <td> {% if analysis.report.metadata.preview and analysis.report.metadata.preview|length > 0  %} <span class="label label-success">Preview found</span> {% else %} <span class="label label-dark">No Preview</span> {% endif %} </td>
        </tr>
        <tr>
            <td>Localization</td>
            <td> {% if analysis.report.metadata.gps.pos %} <span class="label label-success">GPS position</span> {% else %} <span class="label label-dark">No GPS data</span> {% endif %} </td>
        </tr>
        <tr>
            <td>Error Level Analysis (ELA)</td>
            <td> {% if analysis.report.ela  %} <span class="label label-success">Applicable</span> {% else %} <span class="label label-dark">Not applicable</span> {% endif %} </td>
        </tr>
        <tr>
            <td>Signature check</td>
            <td> {% if analysis.report.signatures and analysis.report.signatures|length > 0  %} <span class="label label-success">Signature matches</span> {% else %} <span class="label label-dark">No signature match</span> {% endif %} </td>
        </tr>
    </tbody>
</table>

templates/analyses/report/_exif.html
<div class="box">
    <ul class="nav nav-pills" id="tab-stat">
        <li class="active">
            <a data-toggle="tab" href="#system-metadata">Exif Metadata</a>
        </li>
    </ul>
    <div class="box">
        <div class="tab-content">
            <div class="tab-pane fade in active" id="system-metadata">
                {% include 'analyses/report/_staticExif.html' %}
            </div>
        </div>
    </div>
</div>

templates/analyses/report/show.html
{% extends "base.html" %}

{% block content %}
    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li>
                <a href="{% url "analyses.views.list_cases" %}"><span class="glyphicon glyphicon-book gi-0x"></span> Cases</a>
            </li>
            <li>
                <a href="{% url "analyses.views.show_case" analysis.case.id "list" %}"><span class="glyphicon glyphicon-list gi-0x"></span>
                    {% if analysis.case.name|length > 70 %}
                        {{ analysis.case.name|slice:":70" }} ...
                    {% else %}
                        {{ analysis.case.name }}
                    {% endif %}
                </a>
            </li>
            <li class="active">
                Report
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>Case <small>
                {% if analysis.case.name|length > 70 %}
                    {{ analysis.case.name|slice:":70" }} ...
                {% else %}
                    {{ analysis.case.name }}
                {% endif %}
            </small></h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <div class="pull-left" style="padding-right: 10px">
                    {% if analysis.thumb_id %}
                        <a href="{% url "analyses.views.image" analysis.image_id %}" class="fancybox">
                            <img src="{% url "analyses.views.image" analysis.thumb_id %}" class="img-rounded media-object">
                        </a>
                    {% else %}
                        <img src="{{ STATIC_URL }}img/no_image_large.jpg" class="img-rounded media-object">
                    {% endif %}
                </div>
                <h2 class="media-heading">Image analysis: {{ analysis.report.hash.md5 }}</h2>
                <div class="btn-group">
                    {% if analysis.favorites.all %}
                        <a href="#" id="{% url "analyses.views.favorite" analysis.id %}" rel="{{ analysis.id }}" data-tooltip="tooltip" title="Favorite" class="btn favorite btn-warning star{{ analysis.id }}"> <span class="glyphicon glyphicon-star"></span></a>
                    {% else %}
                        <a href="#" id="{% url "analyses.views.favorite" analysis.id %}" rel="{{ analysis.id }}" data-tooltip="tooltip" title="Favorite"  class="btn favorite btn-default star{{ analysis.id }}"> <span class="glyphicon glyphicon-star"></span></a>
                    {% endif %}
                    <a href="{% url "analyses.views.image" analysis.image_id %}" class="action_print btn btn-info" data-tooltip="tooltip" title="Print"><span class="glyphicon glyphicon-print"></span> </a>
                    <a class="btn btn-danger btn-delete-report" id="{% url "analyses.views.delete_analysis" analysis.id %}" href="#deleteReport" role="button" data-toggle="modal" data-tooltip="tooltip" title="Delete"> <span class="glyphicon glyphicon-trash"></span></a>
                </div>
                <div class="btn-group pull-right">
                    <a class="btn btn-dark dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="glyphicon glyphicon-export"></span> Export
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url "analyses.views.static_report" analysis.id "pdf" %}"><span class="glyphicon glyphicon-import"></span> PDF report</a>
                            <a href="{% url "analyses.views.static_report" analysis.id "html" %}"><span class="glyphicon glyphicon-file"></span> HTML report</a>
                        </li>
                    </ul>
                </div>
                <div class="btn-group pull-right">
                    <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="glyphicon glyphicon-download-alt"></span> Download
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url "analyses.views.export_json" analysis.id %}"><span class="glyphicon glyphicon-edit"></span> JSON report</a>
                            <a href="{% url "analyses.views.image" analysis.image_id %}"><span class="glyphicon glyphicon-picture"></span> Original Image</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="box tabs-left">
                <ul class="nav nav-pills nav-primary">
                    <li class="active">
                        <a href="#dash" data-toggle="tab">Dashboard</a>
                    </li>
                    <li>
                        <a href="#static" data-toggle="tab">Static</a>
                    </li>
                    {% if analysis.report.metadata.Exif %}
                    <li>
                        <a href="#exif" data-toggle="tab">EXIF</a>
                    </li>
                    {% endif %}
                    {% if analysis.report.metadata.Iptc %}
                    <li>
                        <a href="#iptc" data-toggle="tab">IPTC</a>
                    </li>
                    {% endif %}
                    {% if analysis.report.metadata.Xmp %}
                    <li>
                        <a href="#xmp" data-toggle="tab">XMP</a>
                    </li>
                    {% endif %}
                    {% if analysis.report.metadata.preview and analysis.report.metadata.preview|length > 0  %}
                    <li>
                        <a href="#thumb" data-toggle="tab">Thumb</a>
                    </li>
                    {% endif %}
                    {% if analysis.report.metadata.gps %}
                    <li>
                        <a href="#map" data-toggle="tab">Map</a>
                    </li>
                    {% endif %}
                    {% if analysis.report.ela %}
                    <li>
                        <a href="#ela" data-toggle="tab">ELA</a>
                    </li>
                    {% endif %}
                    {# Similarity detection. #}
                    <li>
                        <a href="#simil" data-toggle="tab">Similarity</a>
                    </li>
                    {% if analysis.report.signatures and analysis.report.signatures|length > 0 %}
                    <li>
                        <a href="#signs" data-toggle="tab">Signatures</a>
                    </li>
                    {% endif %}
                </ul>
                <div class="tab-content">
                    <div class="active tab-pane" id="dash">
                        {% include 'analyses/report/_dashboard.html' %}
                    </div>
                    <div class="tab-pane" id="static">
                        {% include 'analyses/report/_static.html' %}
                    </div>
                    {% if analysis.report.metadata.Exif %}
                    <div id="exif" class="tab-pane">
                        {% include 'analyses/report/_exif.html' %}
                    </div>
                    {% endif %}
                    {% if analysis.report.metadata.Iptc %}
                    <div id="iptc" class="tab-pane">
                        {% include 'analyses/report/_iptc.html' %}
                    </div>
                    {% endif %}
                    {% if analysis.report.metadata.Xmp %}
                    <div id="xmp" class="tab-pane">
                        {% include 'analyses/report/_xmp.html' %}
                    </div>
                    {% endif %}
                    {% if analysis.report.metadata.preview and analysis.report.metadata.preview|length > 0  %}
                    <div id="thumb" class="tab-pane">
                        {% include 'analyses/report/_previews.html' %}
                    </div>
                    {% endif %}
                    {% if analysis.report.metadata.gps %}
                    <div id="map" class="tab-pane">
                        {% include 'analyses/report/_map.html' %}
                    </div>
                    {% endif %}
                    {% if analysis.report.ela %}
                    <div id="ela" class="tab-pane">
                        {% include 'analyses/report/_ela.html' %}
                    </div>
                    {% endif %}
                    {# Similarity detection. #}
                    <div id="simil" class="tab-pane">
                        {% include 'analyses/report/_similarity.html' %}
                    </div>
                    {% if analysis.report.signatures and analysis.report.signatures|length > 0 %}
                    <div id="signs" class="tab-pane">
                        {% include 'analyses/report/_signature.html' %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <br>
            <div>
                <ul id="tags">
                    {% for tag in analysis.tag_set.all %}
                        <li>{{ tag.text }}</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="comment controls">
                {% if analysis.comments.all %}
                    <h3>Comments</h3>
                    <table class="table table-striped table-condensed ">
                        {% for comment in analysis.comments.all %}
                        <tr>
                            <td>
                                <p class="text-info">{{ comment.owner.username }} <small class="pull-right">{{ comment.created_at }}</small></p>
                                <p class="pull-right"><a href="{% url "analyses.views.delete_comment" comment.id %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span> Delete</a></p>
                                {{ comment.message }}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                {% endif %}
                <form method="post" action="{% url "analyses.views.add_comment" analysis.id %}">{% csrf_token %}
                    <textarea class="form-control" name="message" id="id_message" type="text" placeholder="Insert your comment"></textarea>
                    <div class="box">
                        <button class="btn btn-success btn-sm">Save comment</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

    {# CSS #}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.tagit.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/tagit.ui-zendesk.css">
    {# JS #}

    <script src="{{ STATIC_URL }}js/tag-it.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var eventTags = $('#tags');

            eventTags.tagit({
                placeholderText: 'Insert your tags',
                afterTagAdded: function(evt, ui) {
                    if (!ui.duringInitialization) {
                        var tag = eventTags.tagit('tagLabel', ui.tag);
                        $.ajax({
                            headers : {'X-Requested-With' : 'XMLHttpRequest', 'X-CSRFToken' : '{{csrf_token}}'},
                            type:'POST',
                            url:'{% url "analyses.views.add_tag" analysis.id %}',
                            data:'tagName=' + tag
                        });
                    }
                },
                afterTagRemoved: function(evt, ui) {
                    var tag = eventTags.tagit('tagLabel', ui.tag);
                    $.ajax({
                        headers : {'X-Requested-With' : 'XMLHttpRequest', 'X-CSRFToken' : '{{csrf_token}}'},
                        type:'POST',
                        url:'{% url "analyses.views.delete_tag" analysis.id %}',
                        data:'tagName=' + tag
                    });
                }
            });
        });
    </script>

{% include "layout/_modalActionCase.html" %}

{% endblock %}