analyses/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^cases/$", "analyses.views.list_cases"),
    url(r"^cases/new/", "analyses.views.new_case"),
    url(r"^cases/edit/(?P<case_id>[\d]+)/", "analyses.views.edit_case"),
    url(r"^cases/close/(?P<case_id>[\d]+)/", "analyses.views.close_case"),
    url(r"^cases/delete/(?P<case_id>[\d]+)/", "analyses.views.delete_case"),
    url(r"^cases/show/(?P<case_id>[\d]+)/(?P<page_name>[\w]+)/", "analyses.views.show_case"),
    url(r"^cases/(?P<case_id>[\d]+)/images/new/$", "analyses.views.new_image"),
    url(r"^cases/(?P<case_id>[\d]+)/folder/new/$", "analyses.views.new_folder"),
    url(r"^cases/(?P<case_id>[\d]+)/url/new/$", "analyses.views.new_url"),
    url(r"^cases/count_ajax/(?P<case_id>[\d]+)/(?P<analysis_id>[\d]+)/$", "analyses.views.count_new_analysis"),
    url(r"^show/(?P<analysis_id>[\d]+)/$", "analyses.views.show_analysis"),
    url(r"^show/(?P<analysis_id>[\d]+)/hexdump/$", "analyses.views.hex_dump"),
    url(r"^delete/(?P<analysis_id>[\d]+)/$", "analyses.views.delete_analysis"),
    url(r"^images/(?P<page_name>[\w]+)/$", "analyses.views.list_images"),
    url(r"^images/file/(?P<id>[\d\w]+)/$", "analyses.views.image"),
    url(r"^images/favorite/(?P<id>[\d\w]+)/$", "analyses.views.favorite"),
    url(r"^images/comment/(?P<id>[\d]+)/$", "analyses.views.add_comment"),
    url(r"^images/comment/delete/(?P<id>[\d]+)/$", "analyses.views.delete_comment"),
    url(r"^search/(?P<page_name>[\w]+)/$", "analyses.views.search"),
    url(r"^images/tag/add/(?P<id>[\d]+)/$", "analyses.views.add_tag"),
    url(r"^images/tag/delete/(?P<id>[\d]+)/$", "analyses.views.delete_tag"),
    url(r"^show/(?P<analysis_id>[\d]+)/report/(?P<report_type>[\w]+)/$", "analyses.views.static_report"),
    url(r"^show/(?P<analysis_id>[\d]+)/export/json/$", "analyses.views.export_json"),
)

api/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^cases/new$", "api.views.new_case"),
    url(r"^cases/show$", "api.views.show_case"),
    url(r"^images/new$", "api.views.new_image"),
    url(r"^images/report", "api.views.get_report"),
)

ghiro/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r"^$", "analyses.views.dashboard"),
    (r"^users/", include("users.urls")),
    (r"^analyses/", include("analyses.urls")),
    (r"^hashes/", include("hashes.urls")),
    (r"^system/", include("system.urls")),
    (r"^api/", include("api.urls")),
)

analyses/forms.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

import os

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator

from analyses.models import Case, Analysis, Comment
from ghiro.common import check_allowed_content
from lib.utils import get_content_type_from_file

class CaseForm(forms.ModelForm):
    """Case form."""
    class Meta:
        model = Case
        fields = "__all__"

class CommentForm(forms.ModelForm):
    """Comment form."""
    class Meta:
        model = Comment
        fields = "__all__"

class UploadImageForm(forms.ModelForm):
    """Image upload form."""
    image = forms.FileField(required=True)

    class Meta:
        model = Analysis
        fields = ["image"]

    def clean_image(self):
        image = self.cleaned_data.get("image", False)
        if image:
            # File check.
            if image._size > settings.MAX_FILE_UPLOAD:
                raise ValidationError("Image file too large")
            # Type check.
            file_type = get_content_type_from_file(image.temporary_file_path())
            if not check_allowed_content(file_type):
                raise ValidationError("Image type not supported.")
        else:
            raise ValidationError("Image field is mandatory.")

class ImageFolderForm(forms.Form):
    """Folder upload form."""
    path = forms.CharField(required=True)

    def clean_image(self):
        path = self.cleaned_data.get("path", False)
        if path:
            # Checks if it exist.
            if not os.path.exists(path):
                raise ValidationError("Specified path not found.")
            # Checks if is a directory.
            if not os.path.isdir(path):
                raise ValidationError("Specified path is not a directory.")
        else:
            raise ValidationError("URL field is mandatory.")

class UrlForm(forms.Form):
    """Image url form."""
    url = forms.CharField(required=True)

    def clean_url(self):
        url = self.cleaned_data.get("url", False)
        if url:
            validate = URLValidator()
            try:
                validate(url)
            except ValidationError:
                raise ValidationError("Please enter a valid URL")
        else:
            raise ValidationError("Path field is mandatory.")

analyses/views.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

import gridfs
import os
import re
import requests
import json
from bson.son import SON
from bson.objectid import ObjectId, InvalidId
from django.template import RequestContext, loader, Context
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe, require_POST
from django.shortcuts import render_to_response, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.utils.timezone import now
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.utils.encoding import force_text
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile

import analyses.forms as forms
from analyses.models import Case, Analysis, Favorite, Comment, Tag
from lib.db import save_file, get_file, mongo_connect
from lib.utils import create_thumb, hexdump, get_content_type_from_file
from users.models import Profile
from ghiro.common import log_activity, check_allowed_content

try:
    import pdfkit
    HAVE_PDFKIT = True
except ImportError:
    HAVE_PDFKIT = False

# Mongo connection.
db = mongo_connect()
fs = gridfs.GridFS(db)

@login_required
def new_case(request):
    """Creates a new case."""
    if request.method == "POST":
        form = forms.CaseForm(request.POST)
        if form.is_valid():
            case = form.save(commit=False)
            case.owner = request.user
            case.save()
            form.save_m2m()
            # Always add owner.
            case.users.add(request.user)
            # Auditing.
            log_activity("C",
                         "Created new case %s" % case.name,
                         request)
            return HttpResponseRedirect(reverse("analyses.views.show_case", args=(case.id, "list")))
    else:
        form = forms.CaseForm()

    return render_to_response("analyses/cases/new.html",
                              {"form": form},
                              context_instance=RequestContext(request))

@login_required
def edit_case(request, case_id):
    """Edit a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if request.user != case.owner and not request.user.is_superuser:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to edit this."},
                                  context_instance=RequestContext(request))

    if case.state == "C":
        return render_to_response("error.html",
                                  {"error": "You cannot edit a closed case."},
                                  context_instance=RequestContext(request))

    if request.method == "POST":
        form = forms.CaseForm(request.POST, instance=case)
        if form.is_valid():
            case = form.save(commit=False)
            case.owner = request.user
            case.updated_at = now()
            case.save()
            form.save_m2m()
            # Always add owner.
            case.users.add(request.user)
            # Auditing.
            log_activity("C",
                         "Edited case %s" % case.name,
                         request)
            return HttpResponseRedirect(reverse("analyses.views.show_case", args=(case.id, "list")))
    else:
        form = forms.CaseForm(instance=case)

    # Redirects to case index if requested.
    if request.GET.get("page", None):
        return HttpResponseRedirect(reverse("analyses.views.list_cases"))
    else:
        return render_to_response("analyses/cases/edit.html",
                                  {"form": form, "case": case},
                                  context_instance=RequestContext(request))

@login_required
def close_case(request, case_id):
    """Close a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if request.user != case.owner and not request.user.is_superuser:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to close this. Only owner can close the case."},
                                  context_instance=RequestContext(request))

    if case.state == "C":
        return render_to_response("error.html",
                                  {"error": "You cannot edit an already closed case."},
                                  context_instance=RequestContext(request))

    case.state = "C"
    case.updated_at = now()
    case.save()
    # Auditing.
    log_activity("C",
                 "Closed case %s" % case.name,
                 request)
    return HttpResponseRedirect(reverse("analyses.views.list_cases"))

@require_safe
@login_required
def delete_case(request, case_id):
    """Delete a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if request.user != case.owner and not request.user.is_superuser:
        return render_to_response("error.html",
                                  {"error": "You are not authorized to delete this. Only owner can delete the case."},
                                  context_instance=RequestContext(request))

    # Delete all analysis.
    for image in case.images.all():
        image.delete()
    # Delete case.
    Case.objects.get(pk=case_id).delete()

    # Auditing.
    log_activity("C",
                 "Case %s deleted" % case.name,
                 request)
    return HttpResponseRedirect(reverse("analyses.views.list_cases"))

@require_safe
@login_required
def show_case(request, case_id, page_name):
    """Details about a case."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if not request.user in case.users.all() and not request.user.is_superuser:
        return render_to_response("error.html",
            {"error": "You are not authorized to view this."},
            context_instance=RequestContext(request))

    tasks = Analysis.objects.filter(case=case)

    # Get last image.
    if tasks.filter(state="C").order_by("completed_at").exists():
        last_image = tasks.filter(state="C").order_by("-id")[0].id
    else:
        last_image = 0

    # Filter by status if requested.
    filtering = request.GET.get("filter")
    if filtering == "completed":
        tasks = tasks.filter(Q(state="C") | Q(state="F"))
    page = request.GET.get("page")
    if page_name == "list" or page_name == "thumb":
        tasks = _paginate(tasks, page, 20)
    elif page_name == "owned":
        tasks = tasks.filter(owner=request.user)
        tasks = _paginate(tasks, page, 20)
    elif page_name == "others":
        tasks = tasks.exclude(owner=request.user)
        tasks = _paginate(tasks, page, 20)
    elif page_name == "favorites":
        tasks = tasks.filter(favorites__owner=request.user)
        tasks = _paginate(tasks, page, 20)
    elif page_name == "map":
        # Return all data, lookup on mongo to be faster.
        mongo_results = db.analyses.find({"metadata.gps.pos": {"$exists": True}})
        # Get results (run a bunch of queries to avoid too long sql queries).
        tasks = []
        for result in mongo_results:
            try:
                analyses = Analysis.objects.filter(case=case)
                if not request.user.is_superuser:
                    analyses = analyses.filter(Q(case__owner=request.user) | Q(case__users=request.user))
                tasks.append(analyses.get(analysis_id=result["_id"]))
            except ObjectDoesNotExist:
                continue
    elif page_name == "nude":
        # Return all data, lookup on mongo to be faster.
        mongo_results = db.analyses.find({"nude.nudepy.result": True})
        # Get results (run a bunch of queries to avoid too long sql queries).
        tasks = []
        for result in mongo_results:
            try:
                analyses = Analysis.objects.filter(case=case)
                if not request.user.is_superuser:
                    analyses = analyses.filter(Q(case__owner=request.user) | Q(case__users=request.user))
                tasks.append(analyses.get(analysis_id=result["_id"]))
            except ObjectDoesNotExist:
                continue
        tasks = _paginate(tasks, page, 20)
    elif page_name == "search":
        pass
    else:
        raise Exception

    return render_to_response("analyses/cases/show.html",
                              {"case": case, "tasks": tasks, "last_image": last_image, "pagename": page_name, "filtered": filtering},
                              context_instance=RequestContext(request))

@require_safe
@login_required
def count_new_analysis(request, case_id, analysis_id):
    """Count new analysis."""
    case = get_object_or_404(Case, pk=case_id)
    new_analysis_count = Analysis.objects.filter(case=case).filter(state="C").filter(pk__gt=analysis_id).count()
    return HttpResponse(new_analysis_count)

@require_safe
@login_required
def list_cases(request):
    """Cases index."""
    last = Case.objects.all()
    my = Case.objects.filter(owner=request.user)
    others = Case.objects.exclude(owner=request.user)

    # Only superuser can see all.
    if not request.user.is_superuser:
        last = last.filter(users=request.user)

    # Set sidebar active tab.
    request.session["sidebar_active"] = "side-cases"

    return render_to_response("analyses/cases/index.html",
                              {"my_cases": my, "last_cases": last, "others_cases": others},
                              context_instance=RequestContext(request))

@login_required
def new_image(request, case_id):
    """Upload a new image."""
    case = get_object_or_404(Case, pk=case_id)

    # Security check.
    if not request.user.is_superuser and not request.user in case.users.all():

templates/analyses/images/index.html
{% extends "base.html" %}

{% block content %}
    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li class="active">
                Images
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>Images <small>browse all images</small></h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <ul class="nav nav-pills nav-primary">
                    <li {% if pagename == "list" %} class="active" {% endif %}>
                        <a href="{% url "analyses.views.list_images" "list"%}">List</a>
                    </li>
                    {% if not hide_thumb %}
                        <li {% if pagename == "thumb" %} class="active" {% endif %}>
                            <a href="{% url "analyses.views.list_images" "thumb" %}">Thumbnails</a>
                        </li>
                    {% endif %}
                    <li {% if pagename == "nude" %} class="active" {% endif %}>
                        <a href="{% url "analyses.views.list_images" "nude" %}">Nude detection</a>
                    </li>
                    <li {% if pagename == "map" %} class="active" {% endif %}>
                        <a href="{% url "analyses.views.list_images" "map" %}">Map</a>
                    </li>
                    <li {% if pagename == "favorites" %} class="active" {% endif %}>
                        <a href="{% url "analyses.views.list_images" "favorites" %}">Favorites</a>
                    </li>
                </ul>
                {% if pagename == "list" %}
                    {% include "analyses/cases/_list_image.html" %}
                    <div id="DataTables_Table_0_paginate" class="dataTables_paginate paging_bs_normal">
                        <ul class="pagination pull-right">
                            {% if images %}
                                {% if images.has_previous %}
                                    <li class="prev">
                                        <a href="{% url "analyses.views.list_images" "list" %}?page={{ images.previous_page_number }}">
                                            <span class="glyphicon glyphicon-chevron-left"></span>
                                            Previous
                                        </a>
                                    </li>
                                {% endif %}
                                {% if images.has_next %}
                                    <li class="next">
                                        <a href="{% url "analyses.views.list_images" "list" %}?page={{ images.next_page_number }}">
                                            Next
                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                        </a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                        <div class="pull-left">
                            <div id="DataTables_Table_0_info" class="dataTables_info" role="status" aria-live="polite">Showing {{ images.number }} to {{ images.paginator.num_pages }}</div>
                        </div>
                    </div>
                {% elif pagename == "thumb" %}
                    {% include "analyses/cases/_thum_image.html" %}
                    <div id="DataTables_Table_0_paginate" class="dataTables_paginate paging_bs_normal">
                        {% if images %}
                            <ul class="pagination pull-right">
                                {% if images.has_previous %}
                                    <li class="prev">
                                        <a href="{% url "analyses.views.list_images" "thumb" %}?page={{ images.previous_page_number }}">
                                            <span class="glyphicon glyphicon-chevron-left"></span>
                                            Previous
                                        </a>
                                    </li>
                                {% endif %}
                                {% if images.has_next %}
                                    <li class="next">
                                        <a href="{% url "analyses.views.list_images" "thumb" %}?page={{ images.next_page_number }}">
                                            Next
                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                            <div class="pull-left">
                                <div id="DataTables_Table_0_info" class="dataTables_info" role="status" aria-live="polite">Showing {{ images.number }} to {{ images.paginator.num_pages }}</div>
                            </div>
                        {% else %}
                            <div class="alert alert-info">
                                <strong>Info!</strong>
                                No matching images found.
                            </div>
                        {% endif %}
                    </div>
                {% elif pagename == "nude" %}
                    {% include "analyses/cases/_thum_image.html" %}
                    <div id="DataTables_Table_0_paginate" class="dataTables_paginate paging_bs_normal">
                        {% if images %}
                            <ul class="pagination pull-right">
                                {% if images.has_previous %}
                                    <li class="prev">
                                        <a href="{% url "analyses.views.list_images" "nude" %}?page={{ images.previous_page_number }}">
                                            <span class="glyphicon glyphicon-chevron-left"></span>
                                            Previous
                                        </a>
                                    </li>
                                {% endif %}
                                {% if images.has_next %}
                                    <li class="next">
                                        <a href="{% url "analyses.views.list_images" "nude" %}?page={{ images.next_page_number }}">
                                            Next
                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                            <div class="pull-left">
                                <div id="DataTables_Table_0_info" class="dataTables_info" role="status" aria-live="polite">Showing {{ images.number }} to {{ images.paginator.num_pages }}</div>
                            </div>
                        {% else %}
                            <div class="alert alert-info">
                                <strong>Not found!</strong>
                                No nudity images found.
                            </div>
                        {% endif %}
                    </div>
                {% elif pagename == "map" %}
                    {% include "analyses/cases/_map_image.html" %}
                {% elif pagename == "favorites" %}
                    {% include "analyses/cases/_favorites.html" %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/analyses/images/new_folder.html
{% extends "base.html" %}

{% block content %}
    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li>
                <a href="{% url "analyses.views.list_cases" %}"><span class="glyphicon glyphicon-book gi-0x"></span> Cases</a>
            </li>
             <li>
                <a href="{% url "analyses.views.show_case" case.id "list" %}"><span class="glyphicon glyphicon-th-list gi-0x"></span>
                    {% if case.name|length > 70 %}
                        {{ case.name|slice:":70" }} ...
                    {% else %}
                        {{ case.name }}
                    {% endif %}
                </a>
            </li>
            <li class="active">
                New Folder
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>New folder <small>in
                "{% if case.name|length > 70 %}
                    {{ case.name|slice:":70" }} ...
                {% else %}
                    {{ case.name }}
                {% endif %}" case</small>
            </h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <blockquote>
                    <p>You can load all images in a folder located on Ghiro server, just write the folder path.</p>
                </blockquote>
                <form action="{% url "analyses.views.new_folder" case.id %}" method="post" class="form-inline">{% csrf_token %}
                    <div class="input-append">
                        <input id="id_path" type="text" name="path" class="form-control">
                        <button id="btn_submit" type="submit" class="btn btn-success">
                            Add
                        </button>
                        <a href="{% url "analyses.views.show_case" case.id "list" %}" class="btn btn-default"> Back </a>
                    </div>
                    <span class="help-inline">{{ form.path.errors }}</span>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/analyses/images/new_url.html
{% extends "base.html" %}

{% block content %}
    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li>
                <a href="{% url "analyses.views.list_cases" %}"><span class="glyphicon glyphicon-book gi-0x"></span> Cases</a>
            </li>
             <li>
                <a href="{% url "analyses.views.show_case" case.id "list" %}"><span class="glyphicon glyphicon-th-list gi-0x"></span>
                    {% if case.name|length > 70 %}
                        {{ case.name|slice:":70" }} ...
                    {% else %}
                        {{ case.name }}
                    {% endif %}
                </a>
            </li>
            <li class="active">
                New image URL
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>New image <small>in
                "{% if case.name|length > 70 %}
                    {{ case.name|slice:":70" }} ...
                {% else %}
                    {{ case.name }}
                {% endif %}" case</small>
            </h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <blockquote>
                    <p>Add image URL: this will fetch URL data and process it as image</p>
                </blockquote>
                <form action="{% url "analyses.views.new_url" case.id %}" method="post" class="form-inline">{% csrf_token %}
                    <div class="input-append">
                        <input id="id_path" type="text" name="url" class="form-control" placeholder="http://example.com/image.jpg">
                        <button id="btn_submit" type="submit" class="btn btn-success">Add</button>
                        <a href="{% url "analyses.views.show_case" case.id "list" %}" class="btn btn-default">Back</a>
                    </div>
                    <span class="help-inline">{{ form.url.errors }}</span>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/analyses/images/search.html
{% extends "base.html" %}

{% block content %}
    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li class="active">
                Search
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>Search <small>in all cases or specific case</small></h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <div class="wdgt-header">Enter keywords for your search</div>
                <div class="wdgt-body">
                    {% include "layout/_searchForm.html" with in_case_id=False %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/analyses/images/waiting.html
{% extends "base.html" %}

{% block content %}

    <div class="crumbs">
        <ol class="breadcrumb hidden-xs">
            <li>
                <span class="glyphicon glyphicon-home gi-0x"></span><a href="/">Dashboard</a>
            </li>
            <li>
                <a href="{% url "analyses.views.list_cases" %}"><span class="glyphicon glyphicon-briefcase gi-0x"></span> Cases</a>
            </li>
             <li>
                <a href="{% url "analyses.views.show_case" analysis.case.id "list" %}"><span class="glyphicon glyphicon-book gi-0x"></span>
                    {{ analysis.case.name }}
                </a>
            </li>
            <li class="active">
                Wait...
            </li>
        </ol>
    </div>
</div>

    <div class="content">
        <div class="page-h1">
            <h1>Cases</h1>
        </div>
        <div class="col-md-12">
            <div class="wdgt">
                <script type="text/javascript">
                    setTimeout("location.reload(true);", 2000);
                </script>
                <div>
                    <h3>Processing {{ analysis.file_name }}</h3>
                </div>
                <div>
                    <div class="alert alert-info">
                        <h4>Chipmunks working...</h4>
                        <p>
                            Your analysis task is waiting to be processed. This page will refresh every second, you will be automatically redirect to analysis when ready.
                        </p>
                        <div class="progress progress-info progress-striped active">
                            <div class="bar" style="width: 100%;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}