api/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r"^cases/new$", "api.views.new_case"),
    url(r"^cases/show$", "api.views.show_case"),
    url(r"^images/new$", "api.views.new_image"),
    url(r"^images/report", "api.views.get_report"),
)

ghiro/urls.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r"^$", "analyses.views.dashboard"),
    (r"^users/", include("users.urls")),
    (r"^analyses/", include("analyses.urls")),
    (r"^hashes/", include("hashes.urls")),
    (r"^system/", include("system.urls")),
    (r"^api/", include("api.urls")),
)

hashes/models.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from django.db import models

from analyses.models import Profile, Analysis

class List(models.Model):
    """Hashes list."""
    CIPHERS = (
            ("sha1", "SHA1"),
            ("sha224", "SHA224"),
            ("sha384", "SHA384"),
            ("crc32", "CRC32"),
            ("sha256", "SHA256"),
            ("sha512", "SHA512"),
            ("md5", "MD5")
            )
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    cipher = models.CharField(max_length=6, choices=CIPHERS, db_index=True, null=False, blank=False, default="MD5")
    public = models.BooleanField(default=False)
    owner = models.ForeignKey(Profile, null=False, blank=False, on_delete=models.CASCADE, db_index=True, editable=False, related_name="owned_hashes")
    created_at = models.DateTimeField(auto_now_add=True, editable=False, db_index=True)
    matches = models.ManyToManyField(Analysis, blank=True)

    def is_owner(self, user):
        """Checks if an user is the owner of this object.
        @param user: user instance
        @return: boolean permission
        """
        return user == self.owner

    def can_read(self, user):
        """Checks if an user is allowed to read this object.
        @param user: user instance
        @return: boolean permission
        """
        return user.is_superuser or self.is_owner(user) or self.public

    def can_write(self, user):
        """Checks if an user is allowed to write (create, edit, delete) this object.
        @param user: user instance
        @return: boolean permission
        """
        return user.is_superuser or self.is_owner(user)

class Hash(models.Model):
    """Hashes."""
    value = models.CharField(max_length=255)
    list = models.ForeignKey(List, null=False, blank=False, on_delete=models.CASCADE, db_index=True, editable=False)

system/models.py
# Ghiro - Copyright (C) 2013-2016 Ghiro Developers.
# This file is part of Ghiro.
# See the file 'docs/LICENSE.txt' for license terms.

from datetime import datetime, timedelta
from django.db import models

class UpdateCheck(models.Model):
    """Collection of image analysis."""

    # Update check state.
    STATUSES = (
        ("E", "Error"),
        ("R", "Running"),
        ("A", "Available"),
        ("N", "Not available")
        )
    state = models.CharField(max_length=1, choices=STATUSES, default="R", editable=False, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, db_index=True)

    @staticmethod
    def should_check():
        """Check if application needs to check for new releases."""
        # Test each day.
        if UpdateCheck.objects.filter(created_at__gte=datetime.now()-timedelta(days=1)).order_by("-created_at").count():
            return False
        else:
            return True

templates/layout/_form.html
<div class="form-group form-inline">
    Name
    <div class="controls box">
        {{ form.name }}<span class="help-inline">{{ form.name.errors }}</span>
    </div>
    Description
    <div class="controls box">
        {{ form.description }}<span class="help-inline">{{ form.description.errors }}</span>
    </div>
    Users
    <div class="controls box">
        {{ form.users }}<span class="help-inline">{{ form.users.errors }}</span> <em>Use the CTRL key to select multiple users.</em>
    </div>
    <div class="controls box">
        <button id="btn_submit" type="submit" class="btn btn-success">
            Save
        </button>
        <a href="{% url "analyses.views.list_cases" %}" class="btn btn-default">Back</a>
    </div>
</div>

templates/layout/_indexCase.html
<div class="box">
    <table class="table datatables">
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Created at</th>
                <th>Owner</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for case in cases %}
                <tr>
                    <td>
                        <a href="{% url "analyses.views.show_case" case.id "list" %}">
                            {% if case.name|length > 70 %}
                                {{ case.name|slice:":70" }} ...
                            {% else %}
                                {{ case.name }}
                            {% endif %}
                        </a>
                    </td>
                    <td>{{ case.get_state_display }}</td>
                    <td>{{ case.created_at }}</td>
                    <td>{{ case.owner.username }}</td>
                    <td>
                        {% if case.state == "C" %}
                            <a class="btn btn-soft" title="No actions available" disabled="disabled"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a class="btn btn-warning" title="Case already closed" disabled="disabled"><span class="glyphicon glyphicon-remove"></span></a>
                            <a class="btn btn-danger btn-delete-case" id="{% url "analyses.views.delete_case" case.id %}" data-tooltip="tooltip" title="Delete case" href="#delete" data-target="#delete" data-toggle="modal"><span class="glyphicon glyphicon-trash"></span></a>
                        {% else %}
                            <a class="btn btn-tbl btn-soft" href="{% url "analyses.views.edit_case" case.id %}" data-tooltip="tooltip" title="Edit case"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a class="btn btn-tbl btn-warning btn-close-case" id="{% url "analyses.views.close_case" case.id %}" data-tooltip="tooltip" title="Close case" data-target="#close" data-toggle="modal"><span class="glyphicon glyphicon-remove"></span></a>
                            <a class="btn btn-tbl btn-danger btn-delete-case" id="{% url "analyses.views.delete_case" case.id %}" data-tooltip="tooltip"title="Delete case" data-target="#delete" data-toggle="modal"><span class="glyphicon glyphicon-trash"></span></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/layout/_modalActionCase.html
<div class="modal fade" id="close" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Close the case</h4>
            </div>
            <div class="modal-body">
                Are you sure continue?
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-warning" id="id-close">Close</a>
                <a type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="delete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete the case</h4>
            </div>
            <div class="modal-body">
                Are you sure continue?
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-danger" id="id-delete">Delete</a>
                <a type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteReport" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete the report</h4>
            </div>
            <div class="modal-body">
                Are you sure continue?
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-danger" id="id-delete-report">Delete</a>
                <a type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

templates/layout/_profileForm.html
<div class="wdgt">
    <div class="wdgt-header">Edit profile</div>
    <div class="wdgt-body" style="padding-bottom:10px;">
        <form action="{% url "users.views.admin_edit_user" user.id %}" method="POST">{% csrf_token %}
            <div class="form-group">
                Username (<small><em>Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only</em></small>)
                <div class="controls box">
                    {{ form.username }}<span class="help-inline">{{ form.username.errors }}</span>
                </div>
                Email
                <div class="controls box">
                    {{ form.email }}<span class="help-inline">{{ form.email.errors }}</span>
                </div>
                Last name
                <div class="controls box">
                    {{ form.last_name }}<span class="help-inline">{{ form.last_name.errors }}</span>
                </div>
                First name
                <div class="controls box">
                    {{ form.first_name }}<span class="help-inline">{{ form.first_name.errors }}</span>
                </div>
                <div class="form-group">
                    {{ form.is_active }} Active<span class="help-inline">{{ form.is_active.errors }}</span> - Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
                </div>
                <div class="form-group">
                    {{ form.is_superuser }} Superuser<span class="help-inline">{{ form.is_superuser.errors }}</span> - Designates that this user has all permissions without explicitly assigning them.
                </div>
                <div class="form-group">
                    {{ form.is_staff }} Staff<span class="help-inline">{{ form.is_staff.errors }}</span> - Designates whether the user can log into this admin site.
                </div>
                <div class="form-group">
                    <button id="btn_submit" type="submit" class="btn btn-success">
                        Save
                    </button>
                    <a href="{% url "users.views.admin_show_user" user.id %}" class="btn btn-default"> Back </a>
                </div>
            </div>
        </form>
    </div>
</div>

templates/layout/_searchForm.html
<div class="box">
    <ul class="nav nav-pills nav-primary">
        <li class="active">
            <a href="#property" data-toggle="tab">Property</a>
        </li>
        <li>
            <a href="#location" data-toggle="tab">Location</a>
        </li>
    </ul>
    <div class="tab-content table">
        {% if error%}
            <div class="alert alert-danger box">
                <b>Error</b>: {{ error }}
            </div>
        {% endif %}
        <form id="property" action="{% url "analyses.views.search" "list" %}" method="get" class="tab-pane active">{% csrf_token %}
            <div class="form-group form-inline box">
                <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search by file name" data-content="Search for file names containing this string.">
                    Filename
                </a>
                <div class="controls">
                    <input id="filename" type="text" name="filename" class="form-control width-form-search">
                </div>
            </div>
            <div class="form-group form-inline box">
                <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search by file type" data-content="Search for file type containing this string.">
                    Filetype
                </a>
                <div class="controls">
                    <input id="filetype" type="text" name="filetype" class="form-control width-form-search">
                </div>
            </div>
            <div class="form-group form-inline box">
                <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search by hash" data-content="Search for images with this hash.">
                    Hash
                </a>
                <div class="controls">
                    <select name="cipher" id="id_cipher" style="height: 35px;">
                        <option value="SHA1">SHA1</option>
                        <option value="SHA224">SHA224</option>
                        <option value="SHA384">SHA384</option>
                        <option value="CRC32">CRC32</option>
                        <option value="SHA256">SHA256</option>
                        <option value="SHA512">SHA512</option>
                        <option value="MD5">MD5</option>
                    </select>
                    <input id="hash" type="text" name="hash" class="form-control" style="width: 320px;">
                </div>
            </div>
            <div class="form-group form-inline box">
                <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search by metadata value" data-content="Search for a value contained in a metadata key (key format example 'Exif.Photo.Camera').">
                    Metadata
                </a>
                <div class="controls">
                    <input id="metadata_key" type="text" name="metadata_key" class="form-control" placeholder="METADATA KEY">
                    <input id="metadata_value" type="text" name="metadata_value" class="form-control" placeholder="METADATA VALUE">
                </div>
            </div>
            <div class="form-group form-inline box">
                <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search by signature" data-content="Search for file names containing this string.">
                    Signature
                </a>
                <div class="controls">
                    <input id="signature" type="text" name="signature" class="form-control width-form-search">
                </div>
            </div>
            {# Detects if the search form is called inside a case or not. (Search scope) #}
            {% if in_case_id %}
                <input type="hidden" value="{{ case.id }}" name="in_case" id="in_case">
            {% else %}
                <div class="control-group">
                    <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search in case" data-content="Search only in selected case.">
                        Case
                    </a>
                    <div class="controls">
                        <select style="width: 400px; height: 35px;" name="in_case">
                            <option value="all">All cases</option>
                            {% for case in available_cases %}
                                <option value="{{ case.id }}">{{ case.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            {% endif %}
            <div class="control-group box">
                <a>Match condition</a>
                <div class="controls">
                   <label class="radio">
                        <input type="radio" name="optionsRadios" id="and" value="and" checked>
                        AND
                   </label>
                   <label class="radio">
                        <input type="radio" name="optionsRadios" id="or" value="or">
                        OR
                   </label>
                </div>
            </div>
            <div class="form-actions">
                <button id="btn_submit" type="submit" class="btn btn-success">
                    Search
                </button>
            </div>
        </form>
        <form id="location" action="{% url "analyses.views.search" "list" %}" method="get" class="form-horizontal form-model tab-pane">{% csrf_token %}
            <div class="control-group box">
                <a href="#" data-trigger="hover" class="pop" data-toggle="popover" title="Search by location" data-content="Search for photos near this point.">
                    Location
                </a>
                <div class="control-group form-inline">
                    <input id="lat" type="text" name="lat" placeholder="LATITUDE" class="form-control">
                    <input id="long" type="text" name="long" placeholder="LONGITUDE" class="form-control">
                    <input id="dist" type="text" name="dist" placeholder="MAX DISTANCE" class="form-control">
                    {# Detects if the search form is called inside a case or not. (Search scope) #}
                    {% if in_case_id %}
                        <input type="hidden" value="{{ case.id }}" name="in_case" id="in_case">
                    {% endif %}
                </div>
            </div>
            <div class="form-actions">
                <button id="btn_submit" type="submit" class="btn btn-success">
                    Search
                </button>
            </div>
        </form>
    </div>
</div>

templates/layout/_sidebar.html
<div class="left hidden-xs">
    <div class="logo"><img id="logo" src="/static/img/logo/logo_ghiro176x80.png" style="width:135lspx !important; height:52px; !important"></div>
    <div class="sidebar">
        <a href="/" id="side-dashboard" class="btn btn-dark btn-lg-sd" type="button">
            <span class="glyphicon glyphicon-dashboard gi-sidebar" data-tooltip="tooltip" data-placement="bottom" title="Dashboard"></span>
        </a>
        <a href="{% url "analyses.views.list_cases" %}" id="side-cases" class="btn btn-dark btn-lg-sd" type="button">
            <span class="glyphicon glyphicon-book gi-sidebar" data-tooltip="tooltip" data-placement="bottom" title="Cases"></span>
        </a>
        <a href="{% url "analyses.views.list_images" "list" %}" id="side-images" class="btn btn-dark btn-lg-sd" type="button">
            <span class="glyphicon glyphicon-picture gi-sidebar" data-tooltip="tooltip" data-placement="bottom" title="Images"></span>
        </a>
        <a href="{% url "analyses.views.search" "form" %}" id="side-search" class="btn btn-dark btn-lg-sd" type="button">
            <span class="glyphicon glyphicon-search gi-sidebar" data-tooltip="tooltip" data-placement="bottom" title="Search"></span>
        </a>
        <a href="{% url "hashes.views.list_hashes" %}" id="side-hashes" class="btn btn-dark btn-lg-sd" type="button">
            <span class="glyphicon glyphicon-list gi-sidebar" data-tooltip="tooltip" data-placement="bottom" title="Hashes"></span>
        </a>
        {% if request.user.is_stuff or request.user.is_superuser %}
            <a href="{% url "users.views.admin_list_users" %}" id="side-admin" class="btn btn-dark btn-lg-sd" type="button">
                <span class="glyphicon glyphicon-cog gi-sidebar" data-tooltip="tooltip" data-placement="bottom" title="Administration"></span>
            </a>
        {% endif %}
    </div>
</div>

<!-- RESPONSIVE NAVIGATION -->
<div id="secondary" class="btn-group visible-xs">
    <button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown"><span class="icon icon-th-large"></span>&nbsp;&nbsp;Navigation&nbsp;&nbsp;<span class="caret"></span></button>
    <ul class="dropdown-menu dropdown-info pull-right" role="menu">
        <li><a href="/">Dashboard</a></li>
        <li><a href="{% url "analyses.views.list_cases" %}">Cases</a></li>
        <li><a href="{% url "analyses.views.list_images" "list" %}">Images</a></li>
        <li class="divider" style="border-bottom:1px solid #ddd; margin:0px; margin-top:5px;"></li>
        <li><a href="{% url "analyses.views.search" "form" %}">Search</a></li>
        <li><a href="{% url "hashes.views.list_hashes" %}">Hash</a></li>
        {% if request.user.is_stuff or request.user.is_superuser %}
        <li><a href="{% url "users.views.admin_list_users" %}">Admin</a></li>
        {% endif %}
    </ul>
</div>
<div id="secondary-search" class="input-icon visible-xs">
    <i class="icon icon-search"></i>
    <input class="form-control form-warning input-sm" type="text">
</div>
<div class="right">
    <div class="nav">
        <div class="bar">
            <div class="logo-small visible-xs"><img src="/static/img/logo/logo_ghiro77x35.png"></div>
            <ul class="nav nav-pills hidden-xs">
                <li><a href="{% url "analyses.views.list_cases" %}"><span class="glyphicon glyphicon-briefcase gi-1x"></span>&nbsp; Open cases <span class="label label-primary">{{ open_cases_count }}</span></a></li>
                <li><a><span class="glyphicon glyphicon-book gi-1x"></span>&nbsp; Analyses completed <span class="label label-success">{{ analyses_complete_count }}</span></a></li>
                <li><a><span class="glyphicon glyphicon-time gi-1x"></span>&nbsp; Analyses waiting <span class="label label-warning">{{ analyses_wait_count }}</span></a></li>
            </ul>
            <div class="hov">
                <div class="btn-group">
                    <a class="con" href="" data-toggle="dropdown"><span class="glyphicon glyphicon-user gi-1x"></span></a>
                    <ul class="dropdown-menu pull-right dropdown-profile" role="menu">
                        <li class="title"><span class="glyphicon glyphicon-user gi-1x"></span>&nbsp;&nbsp;Welcome, {{ request.user.username }}!</li>
                        <li><a href="{% url "users.views.profile" %}"><span class="glyphicon glyphicon-user gi-0x"></span>Profile</a></li>
                        <li><a href="{% url "users.views.admin_show_activity" request.user.id %}"><span class="glyphicon glyphicon-tasks gi-0x"></span>Activity</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url "django.contrib.auth.views.logout" %}"><span class="glyphicon glyphicon-log-out gi-0x"></span>Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $("#{{ request.session.sidebar_active }}").removeClass("btn-dark");
            $("#{{ request.session.sidebar_active }}").addClass("btn-primary");
        </script>